version = 0.1
[default.deploy.parameters]
stack_name = "cloudfront-canary-poc"
resolve_s3 = true
s3_prefix = "cloudfront-canary-poc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ReleaseName=\"v2\" ReleaseWeight=\"50\""
image_repositories = []
